# Generated by Django 4.2.13 on 2024-07-06 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Tourist", "0002_initial"),
        ("Attraction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("star_level", models.IntegerField(verbose_name="星级")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="评分"
                    ),
                ),
                ("description", models.TextField(verbose_name="介绍")),
                (
                    "opening_hours",
                    models.CharField(max_length=100, verbose_name="开放时间"),
                ),
                ("popularity", models.IntegerField(verbose_name="热度")),
                ("comment_count", models.IntegerField(verbose_name="评论数")),
                ("address", models.CharField(max_length=200, verbose_name="地址")),
                (
                    "official_phone",
                    models.CharField(max_length=20, verbose_name="官方电话"),
                ),
            ],
            options={
                "verbose_name": "景点",
                "verbose_name_plural": "景点",
                "db_table": "attraction",
                "ordering": ["name"],
                "unique_together": {("name", "address")},
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="评论时间"),
                ),
                ("comment_text", models.TextField(verbose_name="评论内容")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1, max_digits=2, verbose_name="评分"
                    ),
                ),
                ("likes", models.IntegerField(default=0, verbose_name="点赞数")),
                (
                    "optional_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="comments/",
                        verbose_name="可选图片",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="是否精华"),
                ),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="Attraction.attraction",
                        verbose_name="景点",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Tourist.tourist",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
                "db_table": "comment",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="comment_created_66795a_idx"
                    )
                ],
            },
        ),
    ]
