# Generated by Django 4.2.13 on 2024-07-06 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Attraction", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="attraction", unique_together=set(),),
        migrations.AlterField(
            model_name="attraction",
            name="popularity",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="热度",
            ),
        ),
    ]
