# Generated by Django 4.2.13 on 2024-07-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Attraction", "0003_alter_attraction_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attraction",
            name="official_phone",
            field=models.CharField(max_length=100, verbose_name="官方电话"),
        ),
    ]
