# Generated by Django 4.2.13 on 2024-07-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tourist", "0003_remove_frequenttraveler_frequent_traveler_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourist",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("regular", "普通用户"),
                    ("vip", "VIP用户"),
                    ("admin", "网站管理员"),
                    ("agent", "旅行社人员"),
                ],
                default="regular",
                max_length=20,
                verbose_name="用户类型",
            ),
        ),
    ]
