# Generated by Django 5.0.6 on 2024-07-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ag_name', models.CharField(max_length=100, verbose_name='公司名')),
                ('ag_tel', models.CharField(max_length=20, verbose_name='公司电话')),
                ('ag_brief', models.TextField(verbose_name='公司简介')),
            ],
            options={
                'verbose_name': '旅游公司',
                'verbose_name_plural': '旅游公司',
                'db_table': 'agency',
            },
        ),
    ]
