# Generated by Django 5.0.6 on 2024-07-09 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rt_Rq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rq', models.DateField(verbose_name='日期')),
                ('days', models.PositiveIntegerField(verbose_name='持续天数')),
                ('rt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Route.route', verbose_name='线路ID')),
            ],
            options={
                'verbose_name': '线路日期对应',
                'verbose_name_plural': '线路日期对应',
                'db_table': 'rt_rq',
            },
        ),
    ]
