# Generated by Django 5.0.6 on 2024-07-09 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt_name', models.CharField(max_length=100, verbose_name='线路名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('rt_brief', models.TextField(verbose_name='线路简介')),
                ('ag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agency.agency', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '旅游线路',
                'verbose_name_plural': '旅游线路',
                'db_table': 'route',
            },
        ),
    ]
